project/urls.py
from django.contrib import admin
from django.urls import path, include
from project.constants import ROOT

urlpatterns = [
    path("admin/", admin.site.urls),
    
    path(ROOT, include("project.routes.app")),
    path("playlists/", include("project.routes.playlists")),
]

project/routes/playlists.py
from django.urls import path
from project.constants import ROOT
from project.views import playlists

app_name = "playlists"

urlpatterns = [
    path(ROOT, playlists.index, name="index"),
    path("<int:id>/", playlists.view, name="view"),
    path("create/", playlists.create, name="create"),
    path("<int:id>/edit/", playlists.edit, name="edit"),
    path("<int:id>/manage/", playlists.manage, name="manage"),
]

project/views/playlists.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request) -> HttpResponse:
    return render(request, 'pages/playlists/index.html')

def view(request, id) -> HttpResponse:
    return render(request, 'pages/playlists/view.html')

def create(request) -> HttpResponse:
    return render(request, 'pages/playlists/create.html')

def edit(request, id) -> HttpResponse:
    return render(request, 'pages/playlists/edit.html')

def manage(request, id) -> HttpResponse:
    return render(request, 'pages/playlists/manage.html')

templates/layouts/app.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>
			{% block title %}
				Django Marmut
			{% endblock %}
		</title>

		{% comment %}google fonts{% endcomment %}
		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
		<link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700;900&display=swap" rel="stylesheet" />

		{% comment %}tailwind.css{% endcomment %}
		<link rel="stylesheet" href="{% static 'css/styles.css' %}" />
		<script type="text/javascript" src="{% static 'js/index.js' %}" defer></script>
	</head>

	<body class="bg-white text-neutral-900 antialiased leading-5 antialiased font-serif min-h-screen">
		<nav class="mb-6">
			{% include 'partials/navbar.html' %}
		</nav>

		<main class="w-content">
			{% block content %}

			{% endblock %}
		</main>
	</body>
</html>

templates/layouts/guest.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>
			{% block title %}
				Django Marmut
			{% endblock %}
		</title>

		{% comment %}google fonts{% endcomment %}
		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
		<link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700;900&display=swap" rel="stylesheet" />

		{% comment %}tailwind.css{% endcomment %}
		<link rel="stylesheet" href="{% static 'css/styles.css' %}" />
		<script type="text/javascript" src="{% static 'js/index.js' %}" defer></script>
	</head>

	<body class="bg-white text-neutral-900 antialiased leading-5 antialiased font-serif min-h-screen">
		<nav class="mb-6">
			{% include 'partials/guest/navbar.html' %}
		</nav>

		<main class="w-content">
			<div class="grid lg:grid-cols-3 gap-6 min-h-[80vh]">
				<div class="hidden lg:block text-tertiary">
					<div class="bg-secondary rounded-extra h-full flex flex-col space-y-6 items-center justify-center">
						<h2 class="text-2xl text-medium uppercase">Welcome to</h2>
						<div class="bg-white rounded-xl border-2 border-tertiary w-40 aspect-square flex items-center justify-center">
							<img src="{% static 'images/logo.png' %}" alt="logo" class="w-24" />
						</div>
						<h2 class="text-2xl text-medium uppercase">Marmut</h2>
					</div>
				</div>

				<div class="lg:col-span-2">
					{% block content %}

					{% endblock %}
				</div>
			</div>
		</main>
	</body>
</html>

templates/layouts/landing.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>
			{% block title %}
				Django Marmut
			{% endblock %}
		</title>

		{% comment %}google fonts{% endcomment %}
		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
		<link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700;900&display=swap" rel="stylesheet" />

		{% comment %}tailwind.css{% endcomment %}
		<link rel="stylesheet" href="{% static 'css/styles.css' %}" />
		<script type="text/javascript" src="{% static 'js/index.js' %}" defer></script>
	</head>

	<body class="bg-white text-neutral-900 antialiased leading-5 antialiased font-serif min-h-screen">
		{% block content %}

		{% endblock %}
	</body>
</html>

templates/pages/dashboard.html
{% extends 'layouts/app.html' %}
{% load static %}

{% block title %}
	Django Marmut
{% endblock %}

{% block content %}
	<div class="grid lg:grid-cols-3 min-h-[80vh] gap-8">
		<aside class="hidden lg:block">
			{% include 'partials/sidebar.html' %}
		</aside>

		<div class="lg:col-span-2">
			<div class="h-16 mb-8 flex items-end justify-center">
				<h1 class="text-xl font-medium">Your Playlist</h1>
			</div>

			<div class="bg-neutral-200 p-8 rounded-xl custom-shadow">
				<div class="grid grid-cols-2 gap-8">
					<div class="bg-neutral-500 rounded-xl p-8 custom-shadow flex flex-col space-y-4 aspect-[4/3]">
						<h4 class="text-center font-medium text-xl">Fall</h4>

						<div class="flex items-end space-x-4">
							<h3 class="whitespace-nowrap">Songs</h3>
							<div class="w-full h-px bg-neutral-900"></div>
							<h3 class="whitespace-nowrap">32</h3>
						</div>

						<div class="flex items-end space-x-4">
							<h3 class="whitespace-nowrap">Duration</h3>
							<div class="w-full h-px bg-neutral-900"></div>
							<h3 class="whitespace-nowrap">1h 30m</h3>
						</div>
					</div>
					<div class="bg-neutral-500 rounded-xl p-8 custom-shadow flex flex-col space-y-4 aspect-[4/3]">
						<h4 class="text-center font-medium text-xl">Summer</h4>

						<div class="flex items-end space-x-4">
							<h3 class="whitespace-nowrap">Songs</h3>
							<div class="w-full h-px bg-neutral-900"></div>
							<h3 class="whitespace-nowrap">32</h3>
						</div>

						<div class="flex items-end space-x-4">
							<h3 class="whitespace-nowrap">Duration</h3>
							<div class="w-full h-px bg-neutral-900"></div>
							<h3 class="whitespace-nowrap">1h 30m</h3>
						</div>
					</div>
					<div class="bg-neutral-500 rounded-xl p-8 custom-shadow flex flex-col space-y-4 aspect-[4/3]">
						<h4 class="text-center font-medium text-xl">Winter</h4>

						<div class="flex items-end space-x-4">
							<h3 class="whitespace-nowrap">Songs</h3>
							<div class="w-full h-px bg-neutral-900"></div>
							<h3 class="whitespace-nowrap">32</h3>
						</div>

						<div class="flex items-end space-x-4">
							<h3 class="whitespace-nowrap">Duration</h3>
							<div class="w-full h-px bg-neutral-900"></div>
							<h3 class="whitespace-nowrap">1h 30m</h3>
						</div>
					</div>
					<div class="bg-neutral-500 rounded-xl p-8 custom-shadow flex flex-col space-y-4 aspect-[4/3]">
						<h4 class="text-center font-medium text-xl">Spring</h4>

						<div class="flex items-end space-x-4">
							<h3 class="whitespace-nowrap">Songs</h3>
							<div class="w-full h-px bg-neutral-900"></div>
							<h3 class="whitespace-nowrap">32</h3>
						</div>

						<div class="flex items-end space-x-4">
							<h3 class="whitespace-nowrap">Duration</h3>
							<div class="w-full h-px bg-neutral-900"></div>
							<h3 class="whitespace-nowrap">1h 30m</h3>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/pages/index.html
{% extends 'layouts/landing.html' %}
{% load static %}

{% block title %}
	Django Marmut
{% endblock %}

{% block content %}
	<main class="w-full h-screen flex flex-col items-center justify-center relative">
		<div class="absolute top-0 left-0 w-full h-full p-8">
			<div class="bg-secondary rounded-xl w-full h-full"></div>
		</div>

		<div class="relative">
			<div class="bg-secondary rounded-extra h-full flex flex-col space-y-6 items-center justify-center">
				<h2 class="text-4xl text-bold uppercase">
					<span>Welcome to</span>
					<br />
					<span>Marmut - C13</span>
				</h2>

				<div class="bg-white rounded-xl border-2 border-tertiary w-40 aspect-square flex items-center justify-center custom-shadow">
					<img src="{% static 'images/logo.png' %}" alt="logo" class="w-24" />
				</div>

				<a href="{% url 'app:login' %}" class="w-full"><button class="w-full custom-button bg-neutral-200">User</button></a>
				<a href="{% url 'app:register-label' %}" class="w-full"><button class="w-full custom-button bg-neutral-200">Label</button></a>
			</div>
		</div>
	</main>
{% endblock %}

templates/pages/playlists/create.html
{% extends 'layouts/app.html' %}
{% load static %}

{% block title %}
	Django Marmut
{% endblock %}

{% block content %}
	<div class="flex space-x-6 items-center mb-10">
		<div class="w-full h-px bg-neutral-900"></div>
		<h1 class="text-xl whitespace-nowrap">Create Playlist</h1>
		<div class="w-full h-px bg-neutral-900"></div>
	</div>

	<div class="bg-neutral-200 p-8 rounded-xl custom-shadow mb-10">
		<form action="#" method="post" class="min-h-[500px] flex flex-col items-center justify-center">
			{% csrf_token %}
			<div class="flex flex-col w-full max-w-lg mx-auto">
				<div class="mb-4">
					<label for="name" class="custom-label">Playlist Name</label>
					<input type="name" name="name" id="name" class="custom-input bg-secondary custom-shadow-sm" placeholder="Playlist Name" />
				</div>

				<div class="mb-6">
					<label for="text" class="custom-label">Playlist Description</label>
					<textarea name="text" id="text" class="custom-input bg-secondary custom-shadow-sm" placeholder="Playlist Description"></textarea>
				</div>

				<div class="flex justify-center">
					<button type="submit" class="custom-button bg-neutral-500 custom-shadow-sm">Add</button>
				</div>
			</div>
		</form>
	</div>
{% endblock %}

templates/pages/playlists/edit.html
{% extends 'layouts/app.html' %}
{% load static %}

{% block title %}
	Django Marmut
{% endblock %}

{% block content %}
	<div class="flex space-x-6 items-center mb-10">
		<div class="w-full h-px bg-neutral-900"></div>
		<h1 class="text-xl whitespace-nowrap">Edit Playlist</h1>
		<div class="w-full h-px bg-neutral-900"></div>
	</div>

	<div class="bg-neutral-200 p-8 rounded-xl custom-shadow mb-10">
		<form action="#" method="post" class="min-h-[500px] flex flex-col items-center justify-center">
			{% csrf_token %}
			<div class="flex flex-col w-full max-w-lg mx-auto">
				<div class="mb-4">
					<label for="name" class="custom-label">Playlist Name</label>
					<input type="name" name="name" id="name" class="custom-input bg-secondary custom-shadow-sm" placeholder="Playlist Name" value="This is a playlist name" />
				</div>

				<div class="mb-6">
					<label for="text" class="custom-label">Playlist Description</label>
					<textarea name="text" id="text" class="custom-input bg-secondary custom-shadow-sm" placeholder="Playlist Description">This is a playlist description</textarea>
				</div>

				<div class="flex justify-center">
					<button type="submit" class="custom-button bg-neutral-500 custom-shadow-sm">Edit</button>
				</div>
			</div>
		</form>
	</div>
{% endblock %}

templates/pages/playlists/index.html
{% extends 'layouts/app.html' %}
{% load static %}

{% block title %}
	Django Marmut
{% endblock %}

{% block content %}
	<div class="flex space-x-6 items-center mb-10">
		<div class="w-full h-px bg-neutral-900"></div>
		<h1 class="text-xl whitespace-nowrap">Your Playlist</h1>
		<div class="w-full h-px bg-neutral-900"></div>
	</div>

	<div class="bg-neutral-200 p-8 rounded-xl custom-shadow mb-10">
		<div class="grid grid-cols-2 gap-8">
			<div class="bg-neutral-500 rounded-xl p-8 custom-shadow flex flex-col space-y-4">
				<h4 class="text-center font-medium text-xl">Fall</h4>

				<div class="flex items-end space-x-4">
					<h3 class="whitespace-nowrap">Songs</h3>
					<div class="w-full h-px bg-neutral-900"></div>
					<h3 class="whitespace-nowrap">32</h3>
				</div>

				<div class="flex items-end space-x-4">
					<h3 class="whitespace-nowrap">Duration</h3>
					<div class="w-full h-px bg-neutral-900"></div>
					<h3 class="whitespace-nowrap">1h 30m</h3>
				</div>

				<div class="flex justify-center items-center space-x-4">
					<a href="{% url 'playlists:view' '1' %}"><button class="bg-neutral-700 px-4 py-2 rounded-lg text-white border-none focus:outline-none focus:ring-0 focus:border-none focus:shadow-none">Detail</button></a>

					<a href="{% url 'playlists:edit' '1' %}"><button class="bg-neutral-700 px-4 py-2 rounded-lg text-white border-none focus:outline-none focus:ring-0 focus:border-none focus:shadow-none">Edit</button></a>

					<button class="bg-neutral-700 px-4 py-2 rounded-lg text-white border-none focus:outline-none focus:ring-0 focus:border-none focus:shadow-none">Delete</button>
				</div>
			</div>

			<div class="bg-neutral-500 rounded-xl p-8 custom-shadow flex flex-col space-y-4">
				<h4 class="text-center font-medium text-xl">Summer</h4>

				<div class="flex items-end space-x-4">
					<h3 class="whitespace-nowrap">Songs</h3>
					<div class="w-full h-px bg-neutral-900"></div>
					<h3 class="whitespace-nowrap">32</h3>
				</div>

				<div class="flex items-end space-x-4">
					<h3 class="whitespace-nowrap">Duration</h3>
					<div class="w-full h-px bg-neutral-900"></div>
					<h3 class="whitespace-nowrap">1h 30m</h3>
				</div>

				<div class="flex justify-center items-center space-x-4">
					<a href="{% url 'playlists:view' '1' %}"><button class="bg-neutral-700 px-4 py-2 rounded-lg text-white border-none focus:outline-none focus:ring-0 focus:border-none focus:shadow-none">Detail</button></a>

					<a href="{% url 'playlists:edit' '1' %}"><button class="bg-neutral-700 px-4 py-2 rounded-lg text-white border-none focus:outline-none focus:ring-0 focus:border-none focus:shadow-none">Edit</button></a>

					<button class="bg-neutral-700 px-4 py-2 rounded-lg text-white border-none focus:outline-none focus:ring-0 focus:border-none focus:shadow-none">Delete</button>
				</div>
			</div>

			<div class="bg-neutral-500 rounded-xl p-8 custom-shadow flex flex-col space-y-4">
				<h4 class="text-center font-medium text-xl">Winter</h4>

				<div class="flex items-end space-x-4">
					<h3 class="whitespace-nowrap">Songs</h3>
					<div class="w-full h-px bg-neutral-900"></div>
					<h3 class="whitespace-nowrap">32</h3>
				</div>

				<div class="flex items-end space-x-4">
					<h3 class="whitespace-nowrap">Duration</h3>
					<div class="w-full h-px bg-neutral-900"></div>
					<h3 class="whitespace-nowrap">1h 30m</h3>
				</div>

				<div class="flex justify-center items-center space-x-4">
					<a href="{% url 'playlists:view' '1' %}"><button class="bg-neutral-700 px-4 py-2 rounded-lg text-white border-none focus:outline-none focus:ring-0 focus:border-none focus:shadow-none">Detail</button></a>

					<a href="{% url 'playlists:edit' '1' %}"><button class="bg-neutral-700 px-4 py-2 rounded-lg text-white border-none focus:outline-none focus:ring-0 focus:border-none focus:shadow-none">Edit</button></a>

					<button class="bg-neutral-700 px-4 py-2 rounded-lg text-white border-none focus:outline-none focus:ring-0 focus:border-none focus:shadow-none">Delete</button>
				</div>
			</div>

			<div class="bg-neutral-500 rounded-xl p-8 custom-shadow flex flex-col space-y-4">
				<h4 class="text-center font-medium text-xl">Spring</h4>

				<div class="flex items-end space-x-4">
					<h3 class="whitespace-nowrap">Songs</h3>
					<div class="w-full h-px bg-neutral-900"></div>
					<h3 class="whitespace-nowrap">32</h3>
				</div>

				<div class="flex items-end space-x-4">
					<h3 class="whitespace-nowrap">Duration</h3>
					<div class="w-full h-px bg-neutral-900"></div>
					<h3 class="whitespace-nowrap">1h 30m</h3>
				</div>

				<div class="flex justify-center items-center space-x-4">
					<a href="{% url 'playlists:view' '1' %}"><button class="bg-neutral-700 px-4 py-2 rounded-lg text-white border-none focus:outline-none focus:ring-0 focus:border-none focus:shadow-none">Detail</button></a>

					<a href="{% url 'playlists:edit' '1' %}"><button class="bg-neutral-700 px-4 py-2 rounded-lg text-white border-none focus:outline-none focus:ring-0 focus:border-none focus:shadow-none">Edit</button></a>

					<button class="bg-neutral-700 px-4 py-2 rounded-lg text-white border-none focus:outline-none focus:ring-0 focus:border-none focus:shadow-none">Delete</button>
				</div>
			</div>
		</div>
	</div>

	<div class="flex justify-center items-center">
		<a href="{% url 'playlists:create' %}"><button class="bg-neutral-700 px-4 py-2 rounded-lg text-white border-none focus:outline-none focus:ring-0 focus:border-none focus:shadow-none">Add Playlists</button></a>
	</div>
{% endblock %}

templates/pages/playlists/manage.html
{% extends 'layouts/app.html' %}
{% load static %}

{% block title %}
	Django Marmut
{% endblock %}

{% block content %}
	<div class="flex space-x-6 items-center mb-10">
		<div class="w-full h-px bg-neutral-900"></div>
		<h1 class="text-xl whitespace-nowrap">Add Song</h1>
		<div class="w-full h-px bg-neutral-900"></div>
	</div>

	<div class="bg-neutral-200 p-8 rounded-xl custom-shadow mb-10">
		<div class="grid grid-cols-4 gap-8">
			{% for i in 'abcdefghijklmnopqrst'|make_list %}
				<div class="bg-secondary rounded-xl p-6 custom-shadow-sm flex flex-col space-y-4">
					<h3 class="whitespace-nowrap text-lg font-medium">
						<span>Love</span>
						-
						<span>Keyshia Cole</span>
					</h3>
				</div>
			{% endfor %}
		</div>
	</div>

	<div class="flex justify-center items-center">
		<button class="bg-neutral-700 px-4 py-2 rounded-lg text-white border-none focus:outline-none focus:ring-0 focus:border-none focus:shadow-none">Submit</button>
	</div>
{% endblock %}

templates/pages/playlists/view.html
{% extends 'layouts/app.html' %}
{% load static %}

{% block title %}
	Django Marmut
{% endblock %}

{% block content %}
	<div class="flex space-x-6 items-center mb-10">
		<div class="w-full h-px bg-neutral-900"></div>
		<h1 class="text-xl whitespace-nowrap">Playlist Detail</h1>
		<div class="w-full h-px bg-neutral-900"></div>
	</div>

	<div class="bg-neutral-200 p-8 rounded-xl custom-shadow mb-10">
		<div class="grid grid-cols-3 gap-8">
			<div class="bg-neutral-500 rounded-xl p-8 custom-shadow flex flex-col space-y-4">
				<div class="flex items-end space-x-4">
					<h3 class="whitespace-nowrap">Title</h3>
					<div class="w-full h-px bg-neutral-900"></div>
					<h3 class="whitespace-nowrap">Summer</h3>
				</div>

				<div class="flex items-end space-x-4">
					<h3 class="whitespace-nowrap">By</h3>
					<div class="w-full h-px bg-neutral-900"></div>
					<h3 class="whitespace-nowrap">Raquel</h3>
				</div>

				<div class="flex items-end space-x-4">
					<h3 class="whitespace-nowrap">Songs</h3>
					<div class="w-full h-px bg-neutral-900"></div>
					<h3 class="whitespace-nowrap">32 Songs</h3>
				</div>

				<div class="flex items-end space-x-4">
					<h3 class="whitespace-nowrap">Duration</h3>
					<div class="w-full h-px bg-neutral-900"></div>
					<h3 class="whitespace-nowrap">1h 30m</h3>
				</div>

				<div class="flex items-end space-x-4">
					<h3 class="whitespace-nowrap">Description</h3>
					<div class="w-full h-px bg-neutral-900"></div>
					<h3 class="whitespace-nowrap">Empty</h3>
				</div>
			</div>

			<div class="col-span-2">
				<h2 class="text-2xl font-medium text-center mb-8">Songs</h2>

				<div class="flex flex-col space-y-4 items-center">
					{% for i in '012'|make_list %}
						<div class="w-full bg-secondary rounded-xl p-8 custom-shadow-sm">
							<div class="flex items-center justify-between mb-4">
								<h3 class="text-lg text-medium whitespace-nowrap">Love</h3>
								<h3 class="text-lg text-medium whitespace-nowrap">Keyshia Cole</h3>
								<h3 class="text-lg text-medium whitespace-nowrap">1m 34s</h3>
							</div>

							<div class="flex justify-center items-center space-x-4">
								<button class="bg-tertiary px-4 py-2 rounded-lg text-white border-none focus:outline-none focus:ring-0 focus:border-none focus:shadow-none">See</button>

								<button class="bg-tertiary px-4 py-2 rounded-lg text-white border-none focus:outline-none focus:ring-0 focus:border-none focus:shadow-none">Play</button>

								<button class="bg-tertiary px-4 py-2 rounded-lg text-white border-none focus:outline-none focus:ring-0 focus:border-none focus:shadow-none">Delete</button>
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>

	<div class="flex justify-center items-center">
		<a href="{% url 'playlists:manage' '1' %}"><button class="bg-neutral-700 px-4 py-2 rounded-lg text-white border-none focus:outline-none focus:ring-0 focus:border-none focus:shadow-none">Add Songs</button></a>
	</div>
{% endblock %}

templates/pages/subscription.html
{% extends 'layouts/app.html' %}
{% load static %}

{% block title %}
	Django Marmut
{% endblock %}

{% block content %}
	<div class="grid lg:grid-cols-3 min-h-[80vh] gap-8">
		<aside class="hidden lg:block">
			{% include 'partials/sidebar.html' %}
		</aside>

		<div class="lg:col-span-2">
			<div class="h-16 mb-8 flex items-end justify-center">
				<h1 class="text-xl font-medium">Subscriptions List</h1>
			</div>

			<div class="bg-neutral-200 p-8 rounded-xl custom-shadow">
				<div class="grid grid-cols-1 gap-8">
					{% for subscription in subscriptions %}
						<div class="bg-neutral-500 rounded-xl p-8 custom-shadow flex flex-col space-y-4">
							<h4 class="text-center font-medium text-xl">{{ subscription.name }}</h4>

							<ul class="flex flex-col space-y-2">
								{% for feature in subscription.features %}
									<li>{{ feature }}</li>
								{% endfor %}
							</ul>

							<button class="bg-neutral-700 px-4 py-2 rounded-lg text-white border-none focus:outline-none focus:ring-0 focus:border-none focus:shadow-none">USD {{ subscription.price }}$</button>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/partials/guest/navbar.html
<div class="w-content py-4">
	<div class="px-6 py-4 rounded-xl border-2 border-tertiary bg-gradient-to-r from-primary to-secondary">
		<div class="flex items-center space-x-4">
			{% if request.path == '/register/' %}
				<a href="{% url 'app:register' %}" class="text-xl font-medium opacity-50">Sign Up</a>
			{% else %}
				<a href="{% url 'app:register' %}" class="text-xl font-medium">Sign Up</a>
			{% endif %}

			<div class="w-0.5 h-8 bg-tertiary"></div>

			{% if request.path == '/login/' %}
				<a href="{% url 'app:login' %}" class="text-xl font-medium opacity-50">Log In</a>
			{% else %}
				<a href="{% url 'app:login' %}" class="text-xl font-medium">Log In</a>
			{% endif %}
		</div>
	</div>
</div>

templates/partials/navbar.html
<div class="w-content py-4">
	<div class="px-6 py-4 rounded-xl border-2 border-tertiary bg-gradient-to-r from-primary to-secondary flex items-center justify-between">
		<div class="flex items-center space-x-4">
			{% if request.path == '/dashboard/' %}
				<a href="{% url 'app:dashboard' %}" class="text-xl font-medium opacity-50">Dashboad</a>
			{% else %}
				<a href="{% url 'app:dashboard' %}" class="text-xl font-medium">Dashboad</a>
			{% endif %}
			<div class="w-0.5 h-8 bg-tertiary"></div>

			<a href="#" class="text-xl font-medium">Charts</a>
			<div class="w-0.5 h-8 bg-tertiary"></div>

			{% if request.path|slice:':10' == '/playlists' %}
				<a href="{% url 'playlists:index' %}" class="text-xl font-medium opacity-50">Playlists</a>
			{% else %}
				<a href="{% url 'playlists:index' %}" class="text-xl font-medium">Playlists</a>
			{% endif %}
			<div class="w-0.5 h-8 bg-tertiary"></div>

			{% if request.path == '/subscription/' %}
				<a href="{% url 'app:subscription' %}" class="text-xl font-medium opacity-50">Subscriptions</a>
			{% else %}
				<a href="{% url 'app:subscription' %}" class="text-xl font-medium">Subscriptions</a>
			{% endif %}
			<div class="w-0.5 h-8 bg-tertiary"></div>

			<a href="#" class="text-xl font-medium">Logout</a>
		</div>

		<div class="flex items-center space-x-4">
			<input type="text" placeholder="Search..." class="bg-neutral-500 px-4 py-2 rounded-lg text-white border-none focus:outline-none focus:ring-0 focus:border-none focus:shadow-none placeholder-neutral-400" />
		</div>
	</div>
</div>